---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pwpush-data-pvc
  namespace: pwpush
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem
  volumeName: pwpush-data-pvc
...
