apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pwpush-db-pvc
  namespace: pwpush
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2  # Change this to match your OpenShift storage class
